In [140]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [141]:
df=pd.read_csv(r'C:\MachineLearning\dataset\movies.csv')
df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

## Fetching not Null datas:

In [142]:
df=df[df.notnull()]
df.shape

(34208, 3)

## Droping geners:

In [143]:
movieid_title=df.drop('genres',axis=1)
movieid_title.head()

movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

## changing datatypes:

In [144]:
movieid_title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34208 entries, 0 to 34207
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  34208 non-null  int64 
 1   title    34208 non-null  object
dtypes: int64(1), object(1)
memory usage: 534.6+ KB


In [145]:
movieid_title['title']=movieid_title['title'].astype("str")
movieid_title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34208 entries, 0 to 34207
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  34208 non-null  int64 
 1   title    34208 non-null  object
dtypes: int64(1), object(1)
memory usage: 534.6+ KB


## fetching movieid and title:

In [146]:
title=[]
for i in movieid_title['title']:
        title.append(i.split("(")[0])
movieid_title['title']=title
movieid_title.head()

movieId                         title
0        1                    Toy Story 
1        2                      Jumanji 
2        3             Grumpier Old Men 
3        4            Waiting to Exhale 
4        5  Father of the Bride Part II

## Making columns for journa index:

In [147]:
x=len(df)
for i in range(x):
    journa=df.genres[i].split("|")
    for k in journa:
                movieid_title.at[i,k]=1
movieid_title=movieid_title.fillna(0)

In [148]:
movieid_title.head()

movieId                         title  Adventure  Animation  Children  \
0        1                    Toy Story         1.0        1.0       1.0   
1        2                      Jumanji         1.0        0.0       1.0   
2        3             Grumpier Old Men         0.0        0.0       0.0   
3        4            Waiting to Exhale         0.0        0.0       0.0   
4        5  Father of the Bride Part II         0.0        0.0       0.0   

   Comedy  Fantasy  Romance  Drama  Action  ...  Horror  Mystery  Sci-Fi  \
0     1.0      1.0      0.0    0.0     0.0  ...     0.0      0.0     0.0   
1     0.0      1.0      0.0    0.0     0.0  ...     0.0      0.0     0.0   
2     1.0      0.0      1.0    0.0     0.0  ...     0.0      0.0     0.0   
3     1.0      0.0      1.0    1.0     0.0  ...     0.0      0.0     0.0   
4     1.0      0.0      0.0    0.0     0.0  ...     0.0      0.0     0.0   

   IMAX  Documentary  War  Musical  Western  Film-Noir  (no genres listed)  
0   0.0          0.0  0.0      0.0      0.0        0.0                 0.0  
1   0.0          0.0  0.0      0.0      0.0        0.0                 0.0  
2   0.0          0.0  0.0      0.0      0.0        0.0                 0.0  
3   0.0          0.0  0.0      0.0      0.0        0.0                 0.0  
4   0.0          0.0  0.0      0.0      0.0        0.0                 0.0  

[5 rows x 22 columns]

In [149]:
features=movieid_title.drop(['title','movieId'],1).columns
features

Index(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Mystery', 'Sci-Fi',
       'IMAX', 'Documentary', 'War', 'Musical', 'Western', 'Film-Noir',
       '(no genres listed)'],
      dtype='object')

## fetching  rating data:

In [150]:
df=pd.read_csv(r'C:\MachineLearning\dataset\ratings.csv')

In [151]:
train,test=train_test_split(df.drop('timestamp',axis=1),test_size=0.3,random_state=2,shuffle=True)
df.shape

(22884377, 4)

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22884377 entries, 0 to 22884376
Data columns (total 4 columns):
 #   Column     Dtype  
---  ------     -----  
 0   userId     int64  
 1   movieId    int64  
 2   rating     float64
 3   timestamp  int64  
dtypes: float64(1), int64(3)
memory usage: 698.4 MB


## fetching not null values from ratings:

In [153]:
df=train[df.notnull()]
df.head()

userId  movieId  rating
22729982  246083     1035     4.5
7151899    76837     2372     2.0
14764333  159432      235     5.0
9352009   100930    35836     4.5
18250383  197280     1079     4.0

In [154]:
df.shape

(16019063, 3)

## merging movie journa and rating tables:

In [155]:
user_movie_rating=pd.merge(df,movieid_title,how='left',on='movieId')
user_movie_rating.head()

userId  movieId  rating                     title  Adventure  Animation  \
0  246083     1035     4.5      Sound of Music, The         0.0        0.0   
1   76837     2372     2.0             Fletch Lives         0.0        0.0   
2  159432      235     5.0                  Ed Wood         0.0        0.0   
3  100930    35836     4.5  40-Year-Old Virgin, The         0.0        0.0   
4  197280     1079     4.0     Fish Called Wanda, A         0.0        0.0   

   Children  Comedy  Fantasy  Romance  ...  Horror  Mystery  Sci-Fi  IMAX  \
0       0.0     0.0      0.0      1.0  ...     0.0      0.0     0.0   0.0   
1       0.0     1.0      0.0      0.0  ...     0.0      0.0     0.0   0.0   
2       0.0     1.0      0.0      0.0  ...     0.0      0.0     0.0   0.0   
3       0.0     1.0      0.0      1.0  ...     0.0      0.0     0.0   0.0   
4       0.0     1.0      0.0      0.0  ...     0.0      0.0     0.0   0.0   

   Documentary  War  Musical  Western  Film-Noir  (no genres listed)  
0          0.0  0.0      1.0      0.0        0.0                 0.0  
1          0.0  0.0      0.0      0.0        0.0                 0.0  
2          0.0  0.0      0.0      0.0        0.0                 0.0  
3          0.0  0.0      0.0      0.0        0.0                 0.0  
4          0.0  0.0      0.0      0.0        0.0                 0.0  

[5 rows x 24 columns]

## randomly fetching a main user

In [156]:
user_id=user_movie_rating.userId.sample(1)
user_id

8782659    171720
Name: userId, dtype: int64

## fetching main users data(his movies and ratings)

In [157]:
main_user_rating=user_movie_rating[user_movie_rating['userId'].isin(user_id)]
main_user_rating.shape

(676, 24)

In [158]:
main_user_rating.columns

Index(['userId', 'movieId', 'rating', 'title', 'Adventure', 'Animation',
       'Children', 'Comedy', 'Fantasy', 'Romance', 'Drama', 'Action', 'Crime',
       'Thriller', 'Horror', 'Mystery', 'Sci-Fi', 'IMAX', 'Documentary', 'War',
       'Musical', 'Western', 'Film-Noir', '(no genres listed)'],
      dtype='object')

## checking Datatypes for arithmetic operation

In [159]:
main_user_rating.dtypes

userId                  int64
movieId                 int64
rating                float64
title                  object
Adventure             float64
Animation             float64
Children              float64
Comedy                float64
Fantasy               float64
Romance               float64
Drama                 float64
Action                float64
Crime                 float64
Thriller              float64
Horror                float64
Mystery               float64
Sci-Fi                float64
IMAX                  float64
Documentary           float64
War                   float64
Musical               float64
Western               float64
Film-Noir             float64
(no genres listed)    float64
dtype: object

## Finding similarity index:

In [160]:
array_main_user_movie_journa=np.array(main_user_rating[features])
array_main_user_rating=np.array(main_user_rating['rating']).reshape(-1,1)
array_main_user_rating_journa=array_main_user_rating*array_main_user_movie_journa
array_main_user_rating_journa

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [161]:
main_user_rating_journa_weighted_sum=array_main_user_rating_journa.sum(axis=0)
main_user_rating_journa_weighted_sum

array([ 512.5,   85.5,   99.5,  711.5,  186. ,  332. , 1203.5,  817.5,
        562.5,  863.5,  203.5,  262.5,  368.5,   37. ,   32. ,  162. ,
         55.5,   56. ,   39.5,    0. ])

## Normalizing the weighted sum:

In [162]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
similarity_index=mms.fit_transform(main_user_rating_journa_weighted_sum.reshape(-1,1))

In [163]:
similarity_index

array([[0.4258413 ],
       [0.07104279],
       [0.08267553],
       [0.59119236],
       [0.15454923],
       [0.27586207],
       [1.        ],
       [0.6792688 ],
       [0.46738679],
       [0.71749065],
       [0.16909015],
       [0.21811383],
       [0.30619028],
       [0.03074366],
       [0.02658912],
       [0.1346074 ],
       [0.0461155 ],
       [0.04653095],
       [0.03282094],
       [0.        ]])

## fetching watched and unwatched movie:

In [164]:
watched_movies=main_user_rating['movieId']

In [165]:
unwatched_movie_journa=movieid_title[~movieid_title['movieId'].isin(watched_movies)]
unwatched_movie_journa.shape

(33532, 22)

In [166]:
unwatched_movie_journa.columns

Index(['movieId', 'title', 'Adventure', 'Animation', 'Children', 'Comedy',
       'Fantasy', 'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'IMAX', 'Documentary', 'War', 'Musical', 'Western',
       'Film-Noir', '(no genres listed)'],
      dtype='object')

In [167]:
array_unwatched_movie_journa=np.array(unwatched_movie_journa[features])

In [168]:
array_unwatched_movie_journa.shape,similarity_index.shape

((33532, 20), (20, 1))

In [169]:
unwatched_movie_journa.movieId.value_counts()>1

2047      False
140814    False
122385    False
138424    False
65045     False
          ...  
725       False
6870      False
4823      False
94939     False
131072    False
Name: movieId, Length: 33532, dtype: bool

## Finding movie profile

In [170]:
unwatched_movie_similarity_index=array_unwatched_movie_journa*similarity_index.reshape(1,-1)

In [171]:
weighted_sum_unwatched_movie_similarity_index=unwatched_movie_similarity_index.sum(axis=1)

In [172]:
#normalized_similarity_index=mms.fit_transform(weighted_sum_unwatched_movie_similarity_index.reshape(-1,1))

In [173]:
reshaped_similarity_index=weighted_sum_unwatched_movie_similarity_index.reshape(-1,)

In [174]:
reshaped_similarity_index.shape

(33532,)

In [175]:
highly_recomended=reshaped_similarity_index.max()
highly_recomended

4.3477357706688835

## fetching unwanted movie and merging with rating:

In [176]:
movieId=np.array(unwatched_movie_journa.movieId)

In [177]:
recommendation=pd.DataFrame({'movieId':movieId,'movie_profile':reshaped_similarity_index})

In [185]:
best_recommendation=recommendation.sort_values("movie_profile",ascending=False)[0:100]
best_recommendation

movieId  movie_profile
15392    81132       4.347736
14417    76153       4.020357
14345    75408       4.020357
15838    83266       3.907769
25767   122787       3.881180
...        ...            ...
19387    98558       3.015787
21424   106078       3.013710
10869    49593       3.010802
9793     36529       2.998754
24249   116698       2.994184

[100 rows x 2 columns]

## fetching one highly recommended movie

Above movies can be recommended to the user as they may match their interest

In [186]:
recommmended_movies=movieid_title[movieid_title['movieId'].isin(best_recommendation['movieId'].to_list())]

In [187]:
print("user can be recommended with below movies \n",recommmended_movies['title'])

user can be recommended with below movies 
 19                           Money Train 
143                             Bad Boys 
455                         Getaway, The 
515                            RoboCop 3 
1398                               Metro 
                       ...               
32307                            Holiday 
32433    Confessions of a Dangerous Mind 
33692                     Christmas Town 
33914                            Dilwale 
33973     Sherlock: The Abominable Bride 
Name: title, Length: 100, dtype: object


In [188]:
test.movieId

4988528      3301
3971965       904
2400083       520
4958232     73017
19694220      586
            ...  
14776589     2571
7947015      1013
19698427     3868
2940136      6503
7600709      5618
Name: movieId, Length: 6865314, dtype: int64

In [189]:
l=0
print(len(best_recommendation))
for i in best_recommendation.movieId:
    for j in test.movieId:
        if i==j:
            l+=1
            break
print(l)

100
79 6865314


In [192]:
print("out of {} best recommended movies our customer has watched already {} movies".format(len(best_recommendation),l))

out of 100 best recommended movies our customer has watched already 79 movies
