In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"C:\MachineLearning\dataset\FuelConsumption.csv");
df.head()

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [4]:
df.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')

In [5]:
x=df['FUELCONSUMPTION_COMB_MPG'].values
y=df['CO2EMISSIONS'].values

In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)
xtrain=xtrain.reshape(-1,1)
ytrain=ytrain.reshape(-1,1)
xtest=xtest.reshape(-1,1)
xtest.shape

(214, 1)

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
pipe=make_pipeline(StandardScaler(),LinearRegression())
pipe.fit(xtrain,ytrain)
y_pred=pipe.predict(xtest)
pipe

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.datasets import load_iris
x=load_iris(return_X_y=False)
param={
    'kernel':['rbf','poly'],'C':[0.003,0.05,0.3,0.001],'gamma':[0.1,0.2]
}
search=GridSearchCV(SVC(),param,cv=2)
search.fit(x.data,x.target)
s=search.predict(x.data)
search.cv_results_

{'mean_fit_time': array([0.00049865, 0.00050664, 0.        , 0.        , 0.00049877,
        0.00049853, 0.        , 0.00099766, 0.        , 0.00049806,
        0.        , 0.00049758, 0.        , 0.00051701, 0.        ,
        0.        ]),
 'std_fit_time': array([4.98652458e-04, 5.06639481e-04, 0.00000000e+00, 0.00000000e+00,
        4.98771667e-04, 4.98533249e-04, 0.00000000e+00, 5.96046448e-07,
        0.00000000e+00, 4.98056412e-04, 0.00000000e+00, 4.97579575e-04,
        0.00000000e+00, 5.17010689e-04, 0.00000000e+00, 0.00000000e+00]),
 'mean_score_time': array([0.00049865, 0.00048053, 0.00099719, 0.        , 0.        ,
        0.        , 0.00099742, 0.        , 0.00099754, 0.00049853,
        0.        , 0.00049782, 0.        , 0.        , 0.00099647,
        0.        ]),
 'std_score_time': array([4.98652458e-04, 4.80532646e-04, 3.57627869e-07, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.93390656e-06, 0.00000000e+00,
        3.09944153e-06, 4.98533249e-04, 0.00

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.datasets import load_iris
x=load_iris(return_X_y=False);
pipe=Pipeline(steps=[('std',StandardScaler()),('pca',PCA()),('svc',SVC())])
param={
    'svc__kernel':['rbf','poly','linear'],'svc__C':[0.1,0.6,0.4],"pca__n_components":[2,3]
}
search=GridSearchCV(pipe,param,cv=5)
search.fit(x.data,x.target)
search.predict(x.data)
search.cv_results_

C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

{'mean_fit_time': array([0.00179853, 0.00119524, 0.0011972 , 0.0011991 , 0.00099711,
        0.00146031, 0.00179534, 0.00099673, 0.0012742 , 0.001794  ,
        0.0009974 , 0.00120406, 0.0010047 , 0.00093241, 0.00103693,
        0.00143061, 0.00119672, 0.00099759]),
 'std_fit_time': array([7.47379716e-04, 3.96466266e-04, 3.99899579e-04, 4.03595055e-04,
        1.78416128e-07, 4.51489128e-04, 3.99017761e-04, 1.78161065e-06,
        3.95902464e-04, 3.99181219e-04, 7.00804637e-07, 3.94840298e-04,
        1.40905179e-05, 1.14468869e-04, 6.80427411e-05, 5.34119445e-04,
        3.98826685e-04, 8.31393994e-07]),
 'mean_score_time': array([0.00079741, 0.00039892, 0.00060463, 0.00019965, 0.        ,
        0.00019956, 0.00019946, 0.00060539, 0.00039892, 0.00020666,
        0.        , 0.0006546 , 0.00059738, 0.00039911, 0.00019226,
        0.00019951, 0.        , 0.        ]),
 'std_score_time': array([0.00039871, 0.00048858, 0.00049383, 0.0003993 , 0.        ,
        0.00039911, 0.00039892, 

In [13]:
from sklearn.model_selection import ShuffleSplit,StratifiedShuffleSplit,StratifiedKFold,RepeatedStratifiedKFold,RepeatedKFold,KFold
#cv=check_cv(4)
#cv=KFold(n_splits=3,shuffle=True)
#cv=StratifiedKFold(n_splits=3,shuffle=True,random_state=0)
#cv=StratifiedShuffleSplit(n_splits=3,test_size=0.5,train_size=0.5)
#cv=RepeatedStratifiedKFold(n_splits=5,n_repeats=6)
#cv=RepeatedKFold(n_splits=3,n_repeats=3)
#cv=ShuffleSplit(n_splits=4,test_size=0.5,train_size=0.5)
search=GridSearchCV(pipe,param)
search.fit(x.data,x.target)
search.cv_results_

C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\ashwi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto'

{'mean_fit_time': array([0.00232625, 0.00231457, 0.00199358, 0.00166217, 0.00199461,
        0.00166281, 0.00098944, 0.00099556, 0.00100255, 0.00109665,
        0.00098793, 0.00135843]),
 'std_fit_time': array([4.70865085e-04, 4.51814593e-04, 1.29616312e-06, 4.70302885e-04,
        7.01885292e-07, 4.70415277e-04, 1.08053867e-05, 1.63258223e-06,
        6.78830354e-06, 1.46762382e-04, 1.34311484e-05, 4.27017385e-04]),
 'mean_score_time': array([0.00100676, 0.00033426, 0.0003322 , 0.00066503, 0.00033236,
        0.        , 0.        , 0.        , 0.00033259, 0.        ,
        0.        , 0.00033172]),
 'std_score_time': array([1.27002504e-05, 4.72719053e-04, 4.69796871e-04, 4.70246438e-04,
        4.70021655e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.70358829e-04, 0.00000000e+00, 0.00000000e+00, 4.69122522e-04]),
 'param_pca__n_components': masked_array(data=[2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
              mask=[False, False, False, False, False, False, False, F

In [14]:
from sklearn.model_selection import TimeSeriesSplit
tss=TimeSeriesSplit(n_splits=3,max_train_size=10)
for i,j in tss.split(x.data):
    print(i,j)

[29 30 31 32 33 34 35 36 37 38] [39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62
 63 64 65 66 67 68 69 70 71 72 73 74 75]
[66 67 68 69 70 71 72 73 74 75] [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112]
[103 104 105 106 107 108 109 110 111 112] [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148
 149]


In [15]:
from sklearn.model_selection import PredefinedSplit
ps=PredefinedSplit([0,1,1,0,1,1,1,1,0,0,0]);
for i,j in ps.split(x.data):
    print(i,j);

[1 2 4 5 6 7] [ 0  3  8  9 10]
[ 0  3  8  9 10] [1 2 4 5 6 7]


In [16]:
from sklearn.model_selection import LeavePOut,LeaveOneOut,LeaveOneGroupOut
#lpo=LeavePOut(1)
lpo=LeaveOneGroupOut()
#lpo=LeaveOneOut()
#print(lpo.get_n_splits(x.data))
group=np.random.random(150)
'''for i,j in lpo.split(x.data):
    print(i,j)'''
group

array([0.10605094, 0.0398312 , 0.23034782, 0.85235858, 0.4415067 ,
       0.52989579, 0.88231795, 0.19591982, 0.69342342, 0.67041064,
       0.25603216, 0.57691273, 0.75750228, 0.43777779, 0.08159573,
       0.81110121, 0.83469562, 0.06119507, 0.00519459, 0.08844691,
       0.90212475, 0.92242479, 0.85503381, 0.80902634, 0.25377618,
       0.47377952, 0.37338251, 0.69822312, 0.70706444, 0.5013301 ,
       0.66972124, 0.07490967, 0.04903186, 0.65772553, 0.01669948,
       0.58244651, 0.85880277, 0.50229617, 0.80858525, 0.83045819,
       0.06998075, 0.06612015, 0.6015467 , 0.82910999, 0.44051168,
       0.50350807, 0.58235675, 0.62935441, 0.04415384, 0.85314549,
       0.38503485, 0.21395988, 0.67141774, 0.18640788, 0.55658393,
       0.9801451 , 0.730808  , 0.70968888, 0.61719853, 0.92601148,
       0.38701194, 0.79248006, 0.30891432, 0.75778464, 0.1555997 ,
       0.33104907, 0.60715083, 0.10114666, 0.24416295, 0.0147555 ,
       0.36778603, 0.65986326, 0.19363811, 0.26811484, 0.28713